direktoriMember/Models/SOHeader.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace direktoriMember.Models
{
    public class SOHeader
    {
        public SOHeader()
        {
            this.Tanggal = DateTime.UtcNow.Date;
        }
        public int SOHeaderID { get; set; }
        public DateTime Tanggal { get; set; }
        public string NamaMember { get; set; }

        //lookup Member
        public int MemberID { get; set; }
        public Member Member { get; set; }
    }
}

direktoriMember/Controllers/SOHeaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using direktoriMember.Data;
using direktoriMember.Models;
using direktoriMember.Models.VM;

namespace direktoriMember.Controllers
{
    public class SOHeaderController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SOHeaderController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SOHeader
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.SOHeader.Include(s => s.Member);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: SOHeader/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sOHeader = await _context.SOHeader
                .Include(s => s.Member)
                .FirstOrDefaultAsync(m => m.SOHeaderID == id);

            List<SOLine> lines = new List<SOLine>();
            lines = await _context.SOLine.Where(x => x.SOHeaderID.Equals(sOHeader.SOHeaderID)).ToListAsync();

            SOHeaderLine vm = new SOHeaderLine();
            vm.SOHeader = sOHeader;
            vm.SOLine = lines;

            if (sOHeader == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        // GET: SOHeader/Create
        public IActionResult Create()
        {
            ViewData["MemberID"] = new SelectList(_context.Member, "MemberID", "MemberID");
            return View();
        }

        // POST: SOHeader/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SOHeaderID,Tanggal,NamaMember,MemberID")] SOHeader sOHeader)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sOHeader);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MemberID"] = new SelectList(_context.Member, "MemberID", "MemberID", sOHeader.MemberID);
            return View(sOHeader);
        }

        // GET: SOHeader/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sOHeader = await _context.SOHeader.FindAsync(id);
            if (sOHeader == null)
            {
                return NotFound();
            }
            ViewData["MemberID"] = new SelectList(_context.Member, "MemberID", "MemberID", sOHeader.MemberID);
            return View(sOHeader);
        }

        // POST: SOHeader/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SOHeaderID,Tanggal,NamaMember,MemberID")] SOHeader sOHeader)
        {
            if (id != sOHeader.SOHeaderID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sOHeader);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SOHeaderExists(sOHeader.SOHeaderID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MemberID"] = new SelectList(_context.Member, "MemberID", "MemberID", sOHeader.MemberID);
            return View(sOHeader);
        }

        // GET: SOHeader/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sOHeader = await _context.SOHeader
                .Include(s => s.Member)
                .FirstOrDefaultAsync(m => m.SOHeaderID == id);
            if (sOHeader == null)
            {
                return NotFound();
            }

            return View(sOHeader);
        }

        // POST: SOHeader/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sOHeader = await _context.SOHeader.FindAsync(id);
            _context.SOHeader.Remove(sOHeader);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SOHeaderExists(int id)
        {
            return _context.SOHeader.Any(e => e.SOHeaderID == id);
        }
    }
}

direktoriMember/Controllers/SOLineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using direktoriMember.Data;
using direktoriMember.Models;

namespace direktoriMember.Controllers
{
    public class SOLineController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SOLineController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: SOLine
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.SOLine.Include(s => s.Produk).Include(s => s.SOHeader);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: SOLine/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sOLine = await _context.SOLine
                .Include(s => s.Produk)
                .Include(s => s.SOHeader)
                .FirstOrDefaultAsync(m => m.SOLineID == id);
            if (sOLine == null)
            {
                return NotFound();
            }

            return View(sOLine);
        }

        // GET: SOLine/Create
        public IActionResult Create()
        {
            ViewData["ProdukID"] = new SelectList(_context.Produk, "ProdukID", "ProdukID");
            ViewData["SOHeaderID"] = new SelectList(_context.SOHeader, "SOHeaderID", "SOHeaderID");
            return View();
        }

        // POST: SOLine/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SOLineID,Quantity,ProdukID,SOHeaderID")] SOLine sOLine)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sOLine);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "SOHeader", new { id = sOLine.SOHeaderID });
            }
            ViewData["ProdukID"] = new SelectList(_context.Produk, "ProdukID", "ProdukID", sOLine.ProdukID);
            ViewData["SOHeaderID"] = new SelectList(_context.SOHeader, "SOHeaderID", "SOHeaderID", sOLine.SOHeaderID);
            return View(sOLine);
        }

        // GET: SOLine/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sOLine = await _context.SOLine.FindAsync(id);
            if (sOLine == null)
            {
                return NotFound();
            }
            ViewData["ProdukID"] = new SelectList(_context.Produk, "ProdukID", "ProdukID", sOLine.ProdukID);
            ViewData["SOHeaderID"] = new SelectList(_context.SOHeader, "SOHeaderID", "SOHeaderID", sOLine.SOHeaderID);
            return View(sOLine);
        }

        // POST: SOLine/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SOLineID,Quantity,ProdukID,SOHeaderID")] SOLine sOLine)
        {
            if (id != sOLine.SOLineID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sOLine);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SOLineExists(sOLine.SOLineID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProdukID"] = new SelectList(_context.Produk, "ProdukID", "ProdukID", sOLine.ProdukID);
            ViewData["SOHeaderID"] = new SelectList(_context.SOHeader, "SOHeaderID", "SOHeaderID", sOLine.SOHeaderID);
            return View(sOLine);
        }

        // GET: SOLine/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sOLine = await _context.SOLine
                .Include(s => s.Produk)
                .Include(s => s.SOHeader)
                .FirstOrDefaultAsync(m => m.SOLineID == id);
            if (sOLine == null)
            {
                return NotFound();
            }

            return View(sOLine);
        }

        // POST: SOLine/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sOLine = await _context.SOLine.FindAsync(id);
            _context.SOLine.Remove(sOLine);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SOLineExists(int id)
        {
            return _context.SOLine.Any(e => e.SOLineID == id);
        }
    }
}

direktoriMember/Views/SOHeader/Create.cshtml
@model direktoriMember.Models.SOHeader

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>SOHeader</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Tanggal" class="control-label"></label>
                <input asp-for="Tanggal" class="form-control" />
                <span asp-validation-for="Tanggal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NamaMember" class="control-label"></label>
                <input asp-for="NamaMember" class="form-control" />
                <span asp-validation-for="NamaMember" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberID" class="control-label"></label>
                <select asp-for="MemberID" class ="form-control" asp-items="ViewBag.MemberID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

direktoriMember/Views/SOHeader/Delete.cshtml
@model direktoriMember.Models.SOHeader

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SOHeader</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tanggal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Tanggal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NamaMember)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NamaMember)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Member.MemberID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SOHeaderID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

direktoriMember/Views/SOHeader/Details.cshtml
@model direktoriMember.Models.VM.SOHeaderLine

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>SOHeader</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SOHeader.Tanggal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SOHeader.Tanggal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SOHeader.NamaMember)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SOHeader.NamaMember)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SOHeader.Member)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SOHeader.MemberID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.SOHeader.SOHeaderID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

<div>
    <p>
        <a asp-controller="SOLine" asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Quantity
                </th>
                <th>
                    Produk
                </th>
                <th>
                    SOHeader
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.SOLine)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Produk.ProdukID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SOHeader.SOHeaderID)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.SOLineID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.SOLineID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.SOLineID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

direktoriMember/Views/SOHeader/Edit.cshtml
@model direktoriMember.Models.SOHeader

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>SOHeader</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SOHeaderID" />
            <div class="form-group">
                <label asp-for="Tanggal" class="control-label"></label>
                <input asp-for="Tanggal" class="form-control" />
                <span asp-validation-for="Tanggal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NamaMember" class="control-label"></label>
                <input asp-for="NamaMember" class="form-control" />
                <span asp-validation-for="NamaMember" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MemberID" class="control-label"></label>
                <select asp-for="MemberID" class="form-control" asp-items="ViewBag.MemberID"></select>
                <span asp-validation-for="MemberID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

direktoriMember/Views/SOHeader/Index.cshtml
@model IEnumerable<direktoriMember.Models.SOHeader>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Tanggal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NamaMember)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Member)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Tanggal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NamaMember)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Member.MemberID)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.SOHeaderID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.SOHeaderID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.SOHeaderID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>